name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Remove Old Gradle Wrapper
        run: rm -rf .gradle/ gradle/ && rm -f gradlew gradlew.bat

      - name: Install Latest Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-8.7-bin.zip
          echo "export PATH=/opt/gradle/gradle-8.7/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          gradle --version

      - name: Reinitialize Gradle Wrapper
        run: gradle wrapper --gradle-version 8.7 --distribution-type all

      - name: List directory contents for debugging
        run: ls -la

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: app/build/libs/app.war
     
      - name: check warfile tests
        run: ls -ltrha app/build/libs/app.war
